package investigation.hub.common.web.components;

import com.codeborne.selenide.Condition;
import com.codeborne.selenide.SelenideElement;
import com.smile.components.PageComponent;
import investigation.hub.common.web.components.modals.GeneratedByAiModalComponent;
import investigation.hub.common.web.components.modals.UnsavedChangesModalComponent;
import io.qameta.allure.Step;
import lombok.Getter;
import lombok.extern.log4j.Log4j2;

import java.time.Duration;

import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.$x;

@Log4j2
@PageComponent
@Getter
public class NarrativePageComponent extends PageGeneralComponent {

    private final SelenideElement container = $(".narrative-section-section");
    UnsavedChangesModalComponent unsavedChangesModalComponent = new UnsavedChangesModalComponent();

    @Step("User clicks Generate AI Narrative button")
    public NarrativePageComponent clickGenerateAINarrativeButton() {
        container
                .$x(".//span[contains(text(), 'Generate AI Narrative')]/ancestor::button")
                .as("Generate AI Narrative button")
                .click();
        container
                .$(".dn-loader.smallLoader").shouldBe(Condition.disappear, Duration.ofSeconds(60))
                .as("Wait for AI Narrative loader to disappear");
        log.info("Click Generate AI Narrative button");
        return this;
    }

    @Step("User enters text into Narrative text area")
    public NarrativePageComponent enterTextIntoNarrativeTextArea(String text) {
        SelenideElement narrativeTextArea = container
                .$("textarea[placeholder='Enter Narrative.']")
                .as("Narrative text area");
        narrativeTextArea.clear();
        narrativeTextArea.sendKeys(text);
        log.info("Enter text into Narrative text area");
        return this;
    }

    @Step("User clicks Save button under Narrative text area")
    public NarrativePageComponent clickSaveButton() {
        container
                .$("form button")
                .as("Save button under text area")
                .shouldBe(Condition.enabled, Duration.ofSeconds(60))
                .click();
        log.info("Click save button");
        return this;
    }

    @Step("User clicks 'Generated by AI Disclaimer' link")
    public GeneratedByAiModalComponent clickGeneratedByAiDisclaimerLink() {
        container
                .$("[title='Generated by AI Disclaimer']")
                .as("'Generated by AI Disclaimer' link")
                .click();
        log.info("Click 'Generated by AI Disclaimer' link");
        return new GeneratedByAiModalComponent();
    }

    public boolean isNarrativeHasBeenSavedMessageAppeared() {
        return $x("//p[contains(text(),'Narrative has been saved')]")
                .as("Narrative has been saved message")
                .isDisplayed();
    }

    public String getTextFromNarrativeTextArea() {
        return container
                .$("textarea[placeholder='Enter Narrative.']")
                .as("Narrative text area")
                .getText();
    }

    public boolean isSaveButtonEnabled() {
        return container
                .$("form button")
                .as("Save button under text area")
                .isEnabled();
    }
}
