package investigation.hub.common.web.components.modals;

import com.codeborne.selenide.SelenideElement;
import com.smile.components.ModalComponent;
import investigation.hub.common.web.pages.HelpPage;
import io.qameta.allure.Step;
import lombok.Getter;
import lombok.extern.log4j.Log4j2;

import static com.codeborne.selenide.Condition.enabled;
import static com.codeborne.selenide.Selenide.$x;

@Log4j2
@Getter
@ModalComponent
public class GeneratedByAiModalComponent {

    private final SelenideElement container =
            $x("//div[contains(@class, 'dn-modal-container')][.//h2[text()='Generated by AI']]");

    @Step("User clicks 'Open documentation' link")
    public HelpPage clickOpenDocumentationLink() {
        container
                .$x(".//a[text()='Open documentation']")
                .as("Click 'Open documentation'")
                .shouldBe(enabled)
                .click();
        log.info("Click 'Open documentation' link");
        return new HelpPage();
    }

    @Step("User clicks 'Got it' button")
    public void clickGotItButton() {
        container
                .$x(".//button[.//text()='Got it']")
                .as("'Got it' button")
                .shouldBe(enabled)
                .click();
        log.info("Click 'Got it' button");
    }

    public boolean isGeneratedByAiModalComponentDisplayed() {
        return container.isDisplayed();
    }
}
